# Generated by Django 4.1.2 on 2022-10-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcelerylog',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblcelerylog',
            name='data_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblcelerylog',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblcelerylog',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
