# Generated by Django 4.1.2 on 2022-10-15 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('file_generator', '0004_remove_tblcelerylog_task_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcelerylog',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_results.taskresult'),
        ),
    ]
